### ISSUE TITLE
Close toast on click

### ISSUE THREAD

**Issue by vinicius0026** [vue-comps/vue-toaster#1]
Hi there.

I was looking for a vuejs toaster lib and found yours. Thanks for your work putting this module together.

I think that the default action for a toast is to close on click. Would you mind including this feature?

Also, the default toast appearance is not the what at least I am used to. I understand your goal of building a fully customizable component, but I think the defaults could be a bit different.

Do these topics make sense to you? I could land a PR, but I'm not used to coffee script and I think you could do this faster (and abbreviate the review cycle). Anyway, let me know if I can help.

**Comment by paulpflug** [comment]
hey,

I included the close on click default in 1.1.0. And I changed some stuff, see the [changelog](https://github.com/vue-comps/vue-toaster#changelog)

If you could provide me with a nice default stylesheet I would be more than happy to include it - I'm not that much of a designer I only use the styles of others ;)

**Comment by vinicius0026** [comment]
Thank you very much for the update. Right now I'm kind of busy and unable to evaluate the new version and to submit a PR with a proposal for a stylesheet. But as soon as I return to the project I'm using this module I will certainly do this.
Feel free to close this issue.

**Comment by vinicius0026** [comment]
Hey, I just updated to v2 and it is working great. Thanks.
